name: Python CI Test
on:
  push:
    branches:
      - main
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          export PYTHONPATH=.
          pytest

      - name: Lint with flake8
        run: flake8 .

      - name: Checlk code formatting with black
        run: black --check
