name: Python CI Test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: action/setup-python@v3
        with:
          python-version: '3.9' #Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirenmets.txt # If there is a file "requirenment.txt"

      - name:
        run: |
          pytest
